name = "hammal"
account_id = "5400bee6d7af5f1b99a8487f7fe25438"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-06-08"

kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "8bf534f529554ab88b8e083d2c339c9c" }
]
